### ISSUE TITLE
how to download the finetuned model of the moda networkfilesystem to local?

### ISSUE THREAD

**Issue by Qclover** [modal-labs/llm-finetuning#22]

**Comment by gongy** [comment]
This repo uses `modal.Volume` which is separate from NFS as specified in the title.

For large models, the recommended action is to upload it to S3/GCS if you want to move the weights out of Modal.

To download it, you can set up a Python `http.server` with `modal.Tunnel` with the volume attached and download the files through there.

**Comment by mwaskom** [comment]
Hope that solved your issue!
