### ISSUE TITLE
Does this guide/repo support phi-2 finetuning?

### ISSUE THREAD

**Issue by asmith26** [modal-labs/llm-finetuning#29]
Hi there,

Just thought I'd ask, do you know if this guide supports phi-2 finetuning, https://huggingface.co/microsoft/phi-2?

Many thanks for any help!

**Comment by mwaskom** [comment]
Hi, the [axolotl support matrix](https://github.com/OpenAccess-AI-Collective/axolotl?tab=readme-ov-file#axolotl-supports) suggests partial support for the `phi` family and they have an [example config file](https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/phi/phi2-ft.yml) for `phi-2`. We don't know of any reasons why you couldn't use that example to do some finetuning on modal using the code here, but let us know if you run into problems (we're usually a bit faster to respond [on slack](https://modal.com/slack)).
