### ISSUE TITLE
[bug] inference.py mkdir

### ISSUE THREAD

**Issue by leehanchung** [modal-labs/llm-finetuning#3]
In `inference.py`  `def merge()`, it uses `os.mkdir()`  to create intermediate folders, which python doesnt like.  

use `os.makedirs()` instead.

https://github.com/modal-labs/llama-finetuning/blob/e675b16b902cef931bbf6490f960b228357d1495/inference.py#L20C1-L21C1

**Comment by thundergolfer** [comment]
Thanks @leehanchung, closed by https://github.com/modal-labs/llm-finetuning/commit/562e6a4d5a47c241d58016896ad29bfb2e46ab0b
