### ISSUE TITLE
Can I use train.py on CodeLlama-13b or CodeLlama-34b

### ISSUE THREAD

**Issue by luo647** [modal-labs/llm-finetuning#4]

**Comment by rajivpoddar** [comment]
I also have the same question.

**Comment by GringoDotDev** [comment]
I haven't personally tried it, but from what I can see in the code you just need to add the other models to BASE_MODELS in common.py and invoke train.py with --base set to whatever new key you added.

**Comment by timiil** [comment]
I also have the same question, what hardware (min GPU ram required) can be fine tuning CodeLlama-34b ?

**Comment by mwaskom** [comment]
We now ship this with several example configuration files demonstrating how to use different models!
