### ISSUE TITLE
getting TypeError while launching the training job

### ISSUE THREAD

**Issue by arpitingle** [modal-labs/llm-finetuning#41]
here is the error is get when i run the training following command 
```
modal run --detach src.train --config=config/mistral.yml --data=data/sqlqa.jsonl
```

```
TypeError: _StatefulObject.from_name() got an unexpected keyword argument 
'create_if_missing'
```

the same happens when i try to run the

**Comment by mwaskom** [comment]
Hi, you'll want to update your modal client library (`pip install -U modal`); the syntax in this repository usually reflects the latest changes.
