### ISSUE TITLE
How do you call an inference from Python?

### ISSUE THREAD

**Issue by tonghuikang** [modal-labs/llm-finetuning#77]
Is something like 

```
inference_main("axo-2024-08-11-19-48-32-b6b4", "[INST]This is the prompt[/INST]")
```

enough?

Or do I need to go a roundabout method of making a REST request?

**Comment by mwaskom** [comment]
See our docs on invoking deployed functions here: https://modal.com/docs/guide/trigger-deployed-functions#function-lookup-and-invocation-basics

PS you may want to reach out for help on our [Slack](modal.com/slack) — you'll likely get a faster response as it is monitored much more closely than this issue tracker.
