### ISSUE TITLE
error downloading Mistral 7B Instruct when running in inference

### ISSUE THREAD

**Issue by asapsav** [modal-labs/llm-finetuning#9]
training code worked out of the box for Mistral7B but running in inference raises an error:

```
Loading mistralai/Mistral-7B-Instruct-v0.1 into GPU ... 
Error: DownloadError
Runner failed with exception: Runner has been initializing for too long: 300 seconds
```

**Comment by mwaskom** [comment]
Hi, let us know if you continue seeing this issue but suspect it may have been a transient platform issue and not related to this repository per se!
